### ISSUE TITLE
API not working

### ISSUE THREAD

**Issue by amitkumarhq** [KostaSav/hp-api#47]
![image](https://user-images.githubusercontent.com/94821119/164973002-3f3a123f-4f88-4060-89dd-4a7c1a69d5a3.png)
Today only, as I was working on my discord bot I saw an error coming due to the command which uses this API, and saw this when I went to the API endpoint

**Comment by KostaSav** [comment]
The API is moved to maintenance mode, because the available free hours on Heroku have been used for this month.

I guess that a bot can be keeping the API awake and constantly consuming resources. A solution has to be found, either limit the bot usage or increase the availability, without additional cost.

**Comment by amitkumarhq** [comment]
> The API is moved to maintenance mode, because the available free hours on Heroku have been used for this month.
> 
> I guess that a bot can be keeping the API awake and constantly consuming resources. A solution has to be found, either limit the bot usage or increase the availability, without additional cost.

Try deploying it with https://vercel.app/ maybe it's better idk

**Comment by KostaSav** [comment]
Managed to increase the availability without additional cost, while remaining on Heroku. This should be fine at the moment, issues usually occurred at the end of each month.

If usage increases even more, we will search for another solution.
