### ISSUE TITLE
How can i contribute?

### ISSUE THREAD

**Issue by Allorentee** [KostaSav/hp-api#66]

**Comment by KostaSav** [comment]
Hi @Allorentee ,

You can contribute in any way you think of! 
If you come up with something complex or advanced, we can discuss it first.

Otherwise, you can:

- enrich the data of characters, spells or anything new [here](https://github.com/KostaSav/hp-api/tree/master/data)
- check the [TODO ](https://github.com/KostaSav/hp-api/tree/master/data) section for improvements that can be implemented
- propose ways to spread the word about the HP API 😄
